export const demoProperties = [
  {
    externalId: "prop-marina-01",
    title: "Marina glass residence",
    price: 3450000,
    priceLabel: "AED 3.45M",
    location: "Dubai Marina",
    beds: 2,
    baths: 2,
    area: 1480,
    heroUrl: "https://images.unsplash.com/photo-1494526585095-c41746248156",
    matchScore: 96,
    matchReasons: ["Strong rental moat", "Walkable waterfront"],
    aiSummary: "High-conviction waterfront option with strong liquidity.",
    tags: ["Waterfront", "Turnkey"],
  },
  {
    externalId: "prop-bay-02",
    title: "Business Bay corner unit",
    price: 2820000,
    priceLabel: "AED 2.82M",
    location: "Business Bay",
    beds: 2,
    baths: 3,
    area: 1560,
    heroUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    matchScore: 91,
    matchReasons: ["Fast downtown access", "Strong resale story"],
    aiSummary: "Balanced productivity-plus-lifestyle pick near downtown.",
    tags: ["Resale", "Downtown"],
  },
];
