import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    externalId: v.string(),
    name: v.string(),
    premiumTier: v.string(),
  }).index("by_external_id", ["externalId"]),
  properties: defineTable({
    externalId: v.string(),
    title: v.string(),
    price: v.number(),
    priceLabel: v.string(),
    location: v.string(),
    beds: v.number(),
    baths: v.number(),
    area: v.number(),
    heroUrl: v.string(),
    matchScore: v.number(),
    matchReasons: v.array(v.string()),
    aiSummary: v.string(),
    tags: v.array(v.string()),
  }).index("by_external_id", ["externalId"]),
  property_embeddings: defineTable({
    propertyExternalId: v.string(),
    embeddingProvider: v.string(),
    embeddingRef: v.string(),
  }).index("by_property_external_id", ["propertyExternalId"]),
  saved_properties: defineTable({
    userExternalId: v.string(),
    propertyExternalId: v.string(),
    savedAt: v.number(),
  })
    .index("by_user", ["userExternalId"])
    .index("by_user_property", ["userExternalId", "propertyExternalId"]),
  chat_sessions: defineTable({
    userExternalId: v.string(),
    title: v.string(),
    updatedAt: v.number(),
  }).index("by_user", ["userExternalId"]),
  chat_messages: defineTable({
    sessionExternalId: v.string(),
    role: v.string(),
    kind: v.string(),
    text: v.string(),
    streamState: v.string(),
    relatedPropertyIds: v.array(v.string()),
    createdAt: v.number(),
  }).index("by_session", ["sessionExternalId"]),
  recommendation_batches: defineTable({
    userExternalId: v.string(),
    requestContext: v.string(),
    propertyIds: v.array(v.string()),
    rankingRationale: v.string(),
    createdAt: v.number(),
  }).index("by_user", ["userExternalId"]),
  agent_runs: defineTable({
    userExternalId: v.string(),
    goal: v.string(),
    summary: v.string(),
    diagnostics: v.array(v.string()),
    createdAt: v.number(),
  }).index("by_user", ["userExternalId"]),
  agent_events: defineTable({
    runId: v.id("agent_runs"),
    phase: v.string(),
    message: v.string(),
    createdAt: v.number(),
  }).index("by_run", ["runId"]),
  user_preferences: defineTable({
    userExternalId: v.string(),
    budgetRange: v.array(v.number()),
    locations: v.array(v.string()),
    bedrooms: v.array(v.number()),
    propertyTypes: v.array(v.string()),
    commutePrefs: v.array(v.string()),
    confidence: v.number(),
    updatedFrom: v.string(),
  }).index("by_user", ["userExternalId"]),
  analytics_events: defineTable({
    eventName: v.string(),
    payload: v.string(),
    createdAt: v.number(),
  }).index("by_event_name", ["eventName"]),
});
